# - name: "install node exporter."
#   become: True
#   unarchive:
#     src: https://github.com/prometheus/node_exporter/releases/download/v0.17.0/node_exporter-0.17.0.linux-amd64.tar.gz
#     dest: /tmp
#     remote_src: yes
  # environment:
  #     # - NODE_ENV: production
  #     # - VERSION: "1"
  #     - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
  #     - TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR') }}"
  #     - TYPEORM_ENTITIES: "./backend/dist/modules/domain/**/*.entity{.ts,.js}"
  #     - TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS') }}"
  #     - TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
  #     - TYPEORM_PORT: 5532 #"{{ lookup('env', 'TYPEORM_PORT') }}"
  #     - TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
  #     - TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
  #     - TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
  #     - CORS_WHITELIST: "*"
- name: "Download node exproter"
  become: True
  shell:
    cmd: "wget https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.darwin-amd64.tar.gz; mv node_exporter-1.5.0.darwin-amd64.tar.gz /tmp"
    chdir: .


- name: "move node exproter"
  become: True
  shell:
    cmd: "ls"

- name: "move binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/node_exporter-1.5.0.darwin-amd64.tar.gz
    dest: /usr/local/bin/node_exporter
    remote_src: yes
    mode: '0777'
    
- name: "add node exporter configuration."
  become: true
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/

- name: "enable node_exporter service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: node_exporter
    enabled: yes